import re
import os
import subprocess
import shutil

def replace_function_index(thread_id, mapping, new_code):
    backup_name = f'BACKUP{thread_id}'
    # Backup
    shutil.copyfile(mapping[0], os.path.join(os.path.dirname(mapping[0]), backup_name))
    
    # Replace
    with open(mapping[0], 'r') as file:
        content = file.read()
    with open(mapping[0], 'w') as file:
        #TODO: check these offsets not off by 1.
        file.write(content[:mapping[1]] + new_code + content[mapping[2]+1:])

def undo_function_replacement(thread_id, mapping):
    backup_name = f'BACKUP{thread_id}'
    shutil.copyfile(os.path.join(os.path.dirname(mapping[0]), backup_name), mapping[0])
    os.remove(os.path.join(os.path.dirname(mapping[0]), backup_name))

cuda_to_openmp_func_mapping = {
        'adam+++adam' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/adam-omp/main.cpp', 184, 1239),
        'nms+++generate_nms_bitmap' : ('', 0, 0),
        'lsqt+++gpu_kernel_polynomial' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 28231, 29701),
        'particles+++memSetK' : ('', 0, 0),
        'filter+++filter' : ('', 0, 0),
        'minisweep+++wavefronts' : ('', 0, 0),
        'epistasis+++epi' : ('', 0, 0),
        'reaction+++update' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 9398, 9841),
        'lanczos+++saxpy_inplace_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lanczos-omp/lanczos.cpp', 935, 1138),
        'vol2col+++col2vol_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vol2col-omp/main.cpp', 4047, 6938),
        'rodrigues+++rotate2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/rodrigues-omp/main.cpp', 1084, 1923),
        'bilateral+++bilateralFilter' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bilateral-omp/main.cpp', 131, 1801),
        'softmax+++softMax' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/softmax-omp/main.cpp', 701, 1396),
        'lulesh+++applyAccelerationBoundaryConditionsForNodes' : ('', 0, 0),
        'lid-driven-cavity+++black_kernel' : ('', 0, 0),
        'assert+++perfKernel2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/assert-omp/main.cpp', 1315, 1691),
        'lebesgue+++kernel' : ('', 0, 0),
        'projectile+++CalculateRange' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/projectile-omp/Projectile.cpp', 503, 1382),
        'ace+++boundaryConditionsPhi' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 5604, 6536),
        'hexciton+++comm_empty' : ('', 0, 0),
        'blas-gemm+++matrix_mul' : ('', 0, 0),
        'scan2+++blockAddition' : ('', 0, 0),
        'slu+++RL_onecol_factorizeCurrentCol' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 6838, 7962),
        'atomicPerf+++SingleRangeAtomicOnGlobalMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 851, 1179),
        'mis+++init' : ('', 0, 0),
        'mask+++upperDiagMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 3477, 4177),
        'layout+++AoSKernel' : ('', 0, 0),
        'match+++Match10' : ('', 0, 0),
        'match+++Match2' : ('', 0, 0),
        'nw+++kernel1' : ('', 0, 0),
        'bsearch+++kernel_BS3' : ('', 0, 0),
        'fpc+++fpc_kernel' : ('', 0, 0),
        'fwt+++modulateKernel' : ('', 0, 0),
        'surfel+++surfel_render' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/surfel-omp/main.cpp', 325, 1569),
        'lulesh+++acc_final_force' : ('', 0, 0),
        'iso2dfd+++iso_2dfd_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/iso2dfd-omp/iso2dfd.cpp', 4726, 6233),
        'gmm+++estep1' : ('', 0, 0),
        'deredundancy+++kernel_createIndex7' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 6272, 7651),
        'ans+++phase3_copy_num_symbols_from_aux_to_sync_points' : ('', 0, 0),
        'zmddft+++ker_zmddft_fwd_256x256x256_cu1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/zmddft-omp/main.cpp', 29353, 48318),
        'crs+++gcrs_m_2_w_6_coding_dotprod' : ('', 0, 0),
        'sosfil+++sosfilt' : ('', 0, 0),
        'degrid+++degrid_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/degrid-omp/kernels.cpp', 48, 1359),
        'mdh+++mdh' : ('', 0, 0),
        'dct8x8+++IDCT8x8_kernel' : ('', 0, 0),
        'thomas+++cuThomasBatch' : ('', 0, 0),
        'hexciton+++comm_aosoa_naive_constants_perm' : ('', 0, 0),
        'lsqt+++gpu_chebyshev_01' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 12914, 13636),
        'testSNAP+++reset_ylist' : ('', 0, 0),
        'kmeans+++feature_transpose' : ('', 0, 0),
        'tridiagonal+++sweep_small_systems_global_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/sweep_kernels.cpp', 2485, 4327),
        'simpleSpmv+++mv_dense' : ('', 0, 0),
        'cmp+++init_c' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cmp-omp/main.cpp', 1186, 1462),
        'nlll+++nll_loss_forward_reduce2d_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/nlll-omp/main.cpp', 280, 6266),
        'lanczos+++multiply_inplace_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lanczos-omp/lanczos.cpp', 442, 629),
        'zmddft+++ker_zmddft_fwd_256x256x256_cu2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/zmddft-omp/main.cpp', 48318, 67658),
        'zeropoint+++zero_point' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/zeropoint-omp/main.cpp', 153, 2953),
        'xlqc+++cuda_mat_K_PI_dp' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/xlqc-omp/cuda_rys_dp.cpp', 78996, 81266),
        'hexciton+++comm_aosoa_naive_constants_direct_perm' : ('', 0, 0),
        'langevin+++k1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/langevin-omp/main.cpp', 329, 564),
        'crs+++gcrs_m_4_w_8_coding_dotprod' : ('', 0, 0),
        'conversion+++cvt' : ('', 0, 0),
        'hellinger+++hellinger' : ('', 0, 0),
        'colorwheel+++color' : ('', 0, 0),
        'bwt+++bitonic_sort_step' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bwt-omp/bwt.cpp', 658, 1259),
        'mdh+++mdh3' : ('', 0, 0),
        'kernelLaunch+++KernelWithSmallArgs' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/kernelLaunch-omp/main.cpp', 1594, 1679),
        'libor+++Pathcalc_Portfolio_KernelGPU2' : ('', 0, 0),
        'bfs+++Kernel2' : ('', 0, 0),
        'fluidSim+++lbm' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/fluidSim-omp/kernels.cpp', 1465, 5445),
        'gmm+++mstep_means' : ('', 0, 0),
        'd2q9-bgk+++d2q9_bgk' : ('', 0, 0),
        'cooling+++cool_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cooling-omp/main.cpp', 4263, 4579),
        'lif+++lif' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lif-omp/main.cpp', 1252, 2551),
        'simpleSpmv+++vector_mv_csr' : ('', 0, 0),
        'dp+++dot_product' : ('', 0, 0),
        'hexciton+++comm_aosoa' : ('', 0, 0),
        'murmurhash3+++MurmurHash3_x64_128_kernel' : ('', 0, 0),
        'threadfence+++sum' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/threadfence-omp/main.cpp', 91, 2400),
        'lulesh+++applyMaterialPropertiesForElems' : ('', 0, 0),
        'medianfilter+++ckMedian' : ('', 0, 0),
        'convolution1D+++conv1d' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution1D-omp/main.cpp', 333, 862),
        'slu+++RL_onecol_factorizeCurrentCol_perturb' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 7962, 9234),
        'nqueen+++BP_queens_root_dfs' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/nqueen-omp/main.cpp', 1344, 2843),
        'aidw+++AIDW_Kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/aidw-omp/main.cpp', 966, 2954),
        'chacha20+++test_keystreams' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/chacha20-omp/main.cpp', 423, 1326),
        'tensorT+++tensor_transpose' : ('', 0, 0),
        'hogbom+++k_subtractPSF' : ('', 0, 0),
        'jacobi+++swap_data' : ('', 0, 0),
        'gamma-correction+++gamma_correction' : ('', 0, 0),
        'softmax-online+++softmax_forward_online_kernel3' : ('', 0, 0),
        'crs+++gcrs_m_3_w_6_coding_dotprod' : ('', 0, 0),
        'mt+++boxmuller' : ('', 0, 0),
        'particles+++bitonicSortLocal1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/particles-omp/bitonicSort_kernels.cpp', 4085, 6639),
        'sheath+++rewindParticle' : ('', 0, 0),
        'vmc+++initran' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vmc-omp/vmc.cpp', 3378, 3667),
        'crs+++gcrs_m_2_w_4_coding_dotprod' : ('', 0, 0),
        'atan2+++compute_s' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atan2-omp/main.cpp', 8466, 8911),
        'svd3x3+++svd3_SOA' : ('', 0, 0),
        'gaussian+++fan1' : ('', 0, 0),
        'hypterm+++hypterm_2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hypterm-omp/kernels.cpp', 3450, 6866),
        'shmembench+++benchmark_shmem' : ('', 0, 0),
        'ldpc+++ldpc_cnp_kernel_1st_iter' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ldpc-omp/kernel.cpp', 977, 3789),
        'babelstream+++add_kernel' : ('', 0, 0),
        'convolution3D+++conv3d_s1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution3D-omp/main.cpp', 1325, 2074),
        'bsearch+++kernel_BS2' : ('', 0, 0),
        'pso+++kernelUpdateParticle' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pso-omp/kernel_gpu.cpp', 389, 1025),
        'ans+++phase4_decode_write_output' : ('', 0, 0),
        'sph+++updatePressures' : ('', 0, 0),
        'cfd+++compute_flux' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cfd-omp/euler3d.cpp', 5564, 13651),
        'srad+++compress' : ('', 0, 0),
        'openmp+++addConstant' : ('', 0, 0),
        'sph+++updateAccelerationsFP' : ('', 0, 0),
        'lsqt+++gpu_chebyshev_2x' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 20991, 24233),
        'reaction+++derivative_y2_pbc' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 3404, 4672),
        'bezier-surface+++BezierGPU' : ('', 0, 0),
        'asmooth+++normalizeFilter' : ('', 0, 0),
        'mask+++lowerDiagMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 4200, 4900),
        'crs+++gcrs_m_3_w_5_coding_dotprod' : ('', 0, 0),
        'mis+++findmins' : ('', 0, 0),
        'stddev+++sopKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/stddev-omp/main.cpp', 1356, 2739),
        'particles+++integrateSystemK' : ('', 0, 0),
        'vmc+++propagate' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vmc-omp/vmc.cpp', 1843, 3374),
        'radixsort+++findRadixOffsetsK' : ('', 0, 0),
        'libor+++Pathcalc_Portfolio_KernelGPU' : ('', 0, 0),
        'bsearch+++kernel_BS' : ('', 0, 0),
        'channelShuffle+++ChannelShuffleNCHWKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/channelShuffle-omp/main.cpp', 2041, 2932),
        'mask+++lowerMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 2760, 3454),
        'goulash+++gate' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/goulash-omp/main.cpp', 456, 2271),
        'heat+++initial_value' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/heat-omp/heat.cpp', 1370, 2060),
        'sptrsv+++sptrsv_mix' : ('', 0, 0),
        'pointwise+++elementwise' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pointwise-omp/main.cpp', 1749, 3124),
        'tqs+++TaskQueue_gpu' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tqs-omp/kernel.cpp', 1909, 3586),
        'assert+++testKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/assert-omp/main.cpp', 606, 832),
        'cfd+++initialize_variables' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cfd-omp/euler3d.cpp', 4262, 21810),
        'fresnel+++kernel' : ('', 0, 0),
        'ace+++thermalEquation' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 6539, 7413),
        'grrt+++task2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/grrt-omp/kernels.cpp', 12282, 15496),
        'quantBnB+++kQuantize' : ('', 0, 0),
        'testSNAP+++compute_deidrj' : ('', 0, 0),
        'gmm+++mstep_N' : ('', 0, 0),
        'atomicCost+++wiAtomicOnGlobalMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicCost-omp/main.cpp', 697, 1094),
        'xsbench+++lookup' : ('', 0, 0),
        'linearprobing+++k_hashtable_delete' : ('', 0, 0),
        'overlay+++DetectionOverlayBox' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/overlay-omp/main.cpp', 1280, 2217),
        'minkowski+++minkowski' : ('', 0, 0),
        'ace+++allenCahn' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 4377, 5600),
        'sad+++compute_sad_array' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/sad-omp/main.cpp', 253, 2613),
        'matern+++matern_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/matern-omp/main.cpp', 336, 1206),
        'recursiveGaussian+++SimpleRecursiveRGBA' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/recursiveGaussian-omp/main.cpp', 4181, 5816),
        'hexciton+++comm_manual_aosoa_constants_perm_prefetch' : ('', 0, 0),
        'reaction+++derivative_x2_zeroflux' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 2137, 3303),
        'atomicPerf+++WarpRangeAtomicOnGlobalMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 469, 787),
        'testSNAP+++compute_duidrj' : ('', 0, 0),
        'xlqc+++cuda_mat_K_PI' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/xlqc-omp/cuda_rys_sp.cpp', 81361, 83624),
        'compute-score+++reduction' : ('', 0, 0),
        'lulesh+++integrateStress' : ('', 0, 0),
        'heat+++zero' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/heat-omp/heat.cpp', 2063, 2351),
        's8n+++k_cube_select_four' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/s8n-omp/main.cpp', 2848, 4411),
        'lulesh+++calcKinematicsForElems' : ('', 0, 0),
        'vmc+++zero_stats' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vmc-omp/vmc.cpp', 4304, 4661),
        'zmddft+++ker_zmddft_fwd_256x256x256_cu0' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/zmddft-omp/main.cpp', 11147, 29353),
        'cfd+++compute_step_factor' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cfd-omp/euler3d.cpp', 4612, 5530),
        'simplemoc+++att' : ('', 0, 0),
        'match+++Match5' : ('', 0, 0),
        'reaction+++derivative_z2_zeroflux' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 7436, 8612),
        'hexciton+++comm_refactor' : ('', 0, 0),
        'deredundancy+++kernel_createIndex5' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 3514, 4893),
        'glu+++glu_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/glu-omp/main.cpp', 178, 952),
        'cross+++cross2_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cross-omp/main.cpp', 1253, 2218),
        'qrg+++qrng' : ('', 0, 0),
        'babelstream+++triad_kernel' : ('', 0, 0),
        'channelShuffle+++ChannelShuffleNHWCKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/channelShuffle-omp/main.cpp', 1229, 1931),
        'ccsd-trpdrv+++ccsd_kernel' : ('', 0, 0),
        'ss+++StringSearchLoadBalance' : ('', 0, 0),
        'slu+++RL_onecol_updateSubmat' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 9234, 10749),
        'atomicPerf+++BlockRangeAtomicOnGlobalMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 120, 446),
        'lud+++lud_internal' : ('', 0, 0),
        'hybridsort+++mergepack' : ('', 0, 0),
        'srad+++extract' : ('', 0, 0),
        'keogh+++lb_keogh' : ('', 0, 0),
        'assert+++perfKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/assert-omp/main.cpp', 870, 1312),
        'background-subtract+++updateBackground' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/background-subtract-omp/main.cpp', 809, 1252),
        'popcount+++pc2' : ('', 0, 0),
        'minibude+++fasten_main' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/minibude-omp/kernel.cpp', 353, 6593),
        'ace+++boundaryConditionsU' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 7413, 8327),
        'asta+++PTTWAC_soa_asta' : ('', 0, 0),
        'popcount+++pc1' : ('', 0, 0),
        'particles+++findCellBoundsAndReorderK' : ('', 0, 0),
        'bsearch+++kernel_BS4' : ('', 0, 0),
        'babelstream+++copy_kernel' : ('', 0, 0),
        'haversine+++compute_haversine_distance' : ('', 0, 0),
        'lsqt+++gpu_find_inner_product_1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 6102, 7183),
        'compute-score+++compute' : ('', 0, 0),
        'wedford+++welford_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/wedford-omp/main.cpp', 788, 2476),
        'crs+++gcrs_m_4_w_7_coding_dotprod' : ('', 0, 0),
        'cmp+++init_half' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cmp-omp/main.cpp', 1483, 2223),
        'ddbp+++mapDet2Slice_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 2975, 3981),
        'lid-driven-cavity+++set_vert_pres_BCs' : ('', 0, 0),
        'lulesh+++calcVelocityForNodes' : ('', 0, 0),
        'crs+++gcrs_m_4_w_6_coding_dotprod' : ('', 0, 0),
        'spm+++spm' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/spm-omp/main.cpp', 1072, 3460),
        'mixbench+++benchmark_func' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mixbench-omp/main.cpp', 300, 1437),
        'multimaterial+++ccc_loop2_2' : ('', 0, 0),
        'ntt+++intt_3_64k_modcrt' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ntt-omp/main.cpp', 163, 1401),
        'minisweep+++init_facexy' : ('', 0, 0),
        'reaction+++derivative_y2_zeroflux' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 4775, 5951),
        'hexciton+++comm_aosoa_naive_constants' : ('', 0, 0),
        'ans+++phase1_decode_subseq' : ('', 0, 0),
        'convolution1D+++conv1d_tiled' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution1D-omp/main.cpp', 884, 2044),
        'linearprobing+++k_hashtable_insert' : ('', 0, 0),
        'lsqt+++gpu_apply_current' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 10306, 11417),
        'randomAccess+++initTable' : ('', 0, 0),
        'cross+++cross3_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cross-omp/main.cpp', 2267, 3062),
        'vanGenuchten+++vanGenuchten' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vanGenuchten-omp/main.cpp', 118, 1477),
        'ddbp+++rot_detector_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 2257, 2975),
        'ga+++ga' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ga-omp/main.cpp', 131, 1035),
        'crs+++gcrs_m_3_w_7_coding_dotprod' : ('', 0, 0),
        'winograd+++winograd_conv2d' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/winograd-omp/main.cpp', 57, 2884),
        'keccaktreehash+++ker_Keccak' : ('', 0, 0),
        'deredundancy+++kernel_updateRepresentative' : ('', 0, 0),
        'lulesh+++calcMonotonicQForElems' : ('', 0, 0),
        'babelstream+++dot_kernel' : ('', 0, 0),
        'ans+++phase3_copy_num_symbols_from_sync_points_to_aux' : ('', 0, 0),
        'lulesh+++fb' : ('', 0, 0),
        'atomicPerf+++BlockRangeAtomicOnSharedMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 1241, 1959),
        'ne+++ne' : ('', 0, 0),
        'match+++Match8' : ('', 0, 0),
        'qrg+++icnd' : ('', 0, 0),
        'all-pairs-distance+++k2' : ('', 0, 0),
        'multimaterial+++ccc_loop2' : ('', 0, 0),
        'bn+++genScoreKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bn-omp/kernels.cpp', 332, 2053),
        'popcount+++pc5' : ('', 0, 0),
        'tonemapping+++toneMapping' : ('', 0, 0),
        'cmp+++redux_semblances' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cmp-omp/main.cpp', 4292, 5234),
        'vmc+++SumWithinBlocks' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vmc-omp/vmc.cpp', 4661, 5689),
        'black-scholes+++getOutValOption' : ('', 0, 0),
        'softmax+++softMax2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/softmax-omp/main.cpp', 1399, 2250),
        'heat2d+++dev_lapl_iter' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/heat2d-omp/main.cpp', 919, 1563),
        'hexciton+++comm_aosoa_constants_direct' : ('', 0, 0),
        'slu+++RL_onecol_cleartmpMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 10749, 11702),
        'car+++car' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/car-omp/main.cpp', 212, 2344),
        'lid-driven-cavity+++red_kernel' : ('', 0, 0),
        'tsp+++TwoOpt' : ('', 0, 0),
        'lsqt+++gpu_add_state' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 3095, 3461),
        'wlcpow+++bond_wlcpowallvisc' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/wlcpow-omp/main.cpp', 131, 4782),
        'testSNAP+++compute_yi' : ('', 0, 0),
        'page-rank+++map' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/page-rank-omp/main.cpp', 1507, 2049),
        'hypterm+++hypterm_3' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hypterm-omp/kernels.cpp', 6866, 10282),
        'mriQ+++ComputeQ_GPU' : ('', 0, 0),
        'chemv+++kernel1' : ('', 0, 0),
        'atomicCost+++woAtomicOnGlobalMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicCost-omp/main.cpp', 237, 602),
        'kernelLaunch+++KernelWithLargeArgs' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/kernelLaunch-omp/main.cpp', 1766, 1851),
        'maxpool3d+++maxpool3d' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/maxpool3d-omp/main.cpp', 137, 1237),
        'mcmd+++calculateForceKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mcmd-omp/force_kernel.cpp', 367, 11900),
        'pathfinder+++pathfinder' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pathfinder-omp/main.cpp', 1292, 4660),
        'lsqt+++gpu_copy_state' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 1896, 2264),
        'all-pairs-distance+++k3' : ('', 0, 0),
        'tridiagonal+++cyclic_small_systems_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/cyclic_kernels.cpp', 575, 3749),
        'particles+++collideK' : ('', 0, 0),
        'bonds+++bonds' : ('', 0, 0),
        'rodrigues+++rotate' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/rodrigues-omp/main.cpp', 250, 1084),
        'particles+++calcHashK' : ('', 0, 0),
        'dslash+++make_back' : ('', 0, 0),
        'hexciton+++comm_aosoa_constants' : ('', 0, 0),
        'lsqt+++gpu_chebyshev_1x' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 19719, 20225),
        'geodesic+++kernel_distance' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/geodesic-omp/main.cpp', 2543, 4653),
        'lid-driven-cavity+++calculate_F' : ('', 0, 0),
        'pool+++KernelPool2DGrad' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pool-omp/main.cpp', 542, 3516),
        'pns+++PetrinetKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pns-omp/petri_kernel.cpp', 5375, 5889),
        'crs+++gcrs_m_1_w_6_coding_dotprod' : ('', 0, 0),
        'rainflow+++rainflow_count' : ('', 0, 0),
        'ddbp+++division_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 10368, 10831),
        'perplexity+++sigmas_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/perplexity-omp/main.cpp', 838, 2535),
        'lsqt+++gpu_apply_sz' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 4108, 4587),
        'testSNAP+++set_ulisttot' : ('', 0, 0),
        'knn+++cuInsertionSort' : ('', 0, 0),
        'doh+++hessian_matrix_det' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/doh-omp/main.cpp', 3044, 4620),
        'simpleSpmv+++mv_csr' : ('', 0, 0),
        'triad+++triad' : ('', 0, 0),
        'deredundancy+++kernel_align' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 13231, 20637),
        'ddbp+++bilinear_interpolation_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 5811, 8199),
        'chemv+++kernel0' : ('', 0, 0),
        'bwt+++generate_table' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bwt-omp/bwt.cpp', 82, 355),
        'kalman+++kalman' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/kalman-omp/main.cpp', 3084, 7566),
        'nw+++kernel2' : ('', 0, 0),
        'flip+++flip_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/flip-omp/main.cpp', 261, 1398),
        'bfs+++Kernel' : ('', 0, 0),
        'hwt1d+++dwtHaar1D' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hwt1d-omp/kernel.cpp', 2211, 4702),
        'swish+++SwishGradientKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/swish-omp/main.cpp', 550, 1036),
        'convolution1D+++conv1d_tiled_caching' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution1D-omp/main.cpp', 2066, 3309),
        'fwt+++fwtBatch1Kernel' : ('', 0, 0),
        'morphology+++vhgw_vert' : ('', 0, 0),
        'kernelLaunch+++KernelWithMediumArgs' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/kernelLaunch-omp/main.cpp', 1679, 1766),
        'recursiveGaussian+++RecursiveRGBA' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/recursiveGaussian-omp/main.cpp', 6287, 8892),
        'deredundancy+++kernel_compressData' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 936, 1985),
        'rtm8+++rtm8' : ('', 0, 0),
        'present+++present' : ('', 0, 0),
        'interleave+++add_kernel_interleaved' : ('', 0, 0),
        'aes+++AESEncrypt' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/aes-omp/kernels.cpp', 2128, 4024),
        'ace+++calculateForce' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 2760, 4373),
        'slu+++RL' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 144, 3427),
        'hexciton+++comm_manual_aosoa_constants_direct' : ('', 0, 0),
        'radixsort+++scanExclusiveLocal2K' : ('', 0, 0),
        'lid-driven-cavity+++calc_residual' : ('', 0, 0),
        'mask+++upperMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 2043, 2737),
        'particles+++bitonicSortLocal' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/particles-omp/bitonicSort_kernels.cpp', 1284, 3696),
        'gmm+++constants_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gmm-omp/gaussian_kernel.cpp', 3045, 5233),
        'extrema+++relextrema_1D' : ('', 0, 0),
        'mrc+++MRCGradient' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mrc-omp/main.cpp', 136, 707),
        'lombscargle+++lombscargle' : ('', 0, 0),
        'atan2+++compute_i' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atan2-omp/main.cpp', 8911, 9471),
        'lsqt+++gpu_chebyshev_2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 14795, 16953),
        'hexciton+++comm_aosoa_constants_direct_perm' : ('', 0, 0),
        'binomial+++binomialOptionsKernel' : ('', 0, 0),
        'multimaterial+++ccc_loop1' : ('', 0, 0),
        'rng-wallace+++rng_wallace' : ('', 0, 0),
        's8n+++k_cube_select_two' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/s8n-omp/main.cpp', 1287, 2848),
        'ccs+++compute_bicluster' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ccs-omp/main.cpp', 2371, 7527),
        'lsqt+++gpu_set_zero' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 812, 1121),
        'secp256k1+++secp256k1' : ('', 0, 0),
        'b+tree+++findK' : ('', 0, 0),
        'grrt+++task1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/grrt-omp/kernels.cpp', 8658, 10666),
        'md5hash+++md5hash_kernel' : ('', 0, 0),
        'meanshift+++mean_shift' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/meanshift-omp/main.cpp', 162, 1106),
        'tridiagonal+++pcr_small_systems_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/pcr_kernels.cpp', 659, 3122),
        'hexciton+++comm_aosoa_naive' : ('', 0, 0),
        'reaction+++derivative_x2_pbc' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 612, 2035),
        'meanshift+++mean_shift_tiling' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/meanshift-omp/main.cpp', 1110, 3260),
        'scan+++scan' : ('', 0, 0),
        'radixsort+++scanExclusiveLocal1K' : ('', 0, 0),
        'xlqc+++cuda_mat_J_PI' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/xlqc-omp/cuda_rys_sp.cpp', 79012, 81309),
        'convolution3D+++conv3d_s2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution3D-omp/main.cpp', 2096, 3150),
        'floydwarshall+++floydWarshallPass' : ('', 0, 0),
        'boxfilter+++row_kernel' : ('', 0, 0),
        'henry+++insertions' : ('', 0, 0),
        'deredundancy+++kernel_makeTable' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 9325, 9918),
        'lud+++lud_diagonal' : ('', 0, 0),
        'recursiveGaussian+++Transpose' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/recursiveGaussian-omp/main.cpp', 1748, 3780),
        'wyllie+++wyllie' : ('', 0, 0),
        'nms+++reduce_nms_bitmap' : ('', 0, 0),
        'crs+++gcrs_m_4_w_5_coding_dotprod' : ('', 0, 0),
        'pointwise+++init' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pointwise-omp/main.cpp', 3389, 3652),
        'radixsort+++uniformUpdateK' : ('', 0, 0),
        'sampling+++exact_rows_kernel' : ('', 0, 0),
        'sph+++updateAccelerationsBP' : ('', 0, 0),
        'lulesh+++calcMonotonicQGradientsForElems' : ('', 0, 0),
        'loopback+++tausworthe_lookback' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/loopback-omp/kernels.cpp', 2393, 4406),
        'split+++radixSortBlocksKeysK' : ('', 0, 0),
        'ldpc+++ldpc_vnp_kernel_last_iter' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ldpc-omp/kernel.cpp', 8547, 10283),
        'hmm+++viterbi' : ('', 0, 0),
        'babelstream+++init_kernel' : ('', 0, 0),
        'hotspot3D+++hotspot3d' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hotspot3D-omp/3D.cpp', 1165, 2987),
        'hexciton+++comm_manual_aosoa_direct' : ('', 0, 0),
        'b+tree+++findRangeK' : ('', 0, 0),
        'mask+++windowMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 1049, 2020),
        'dslash+++dslash' : ('', 0, 0),
        'fwt+++fwtBatch2Kernel' : ('', 0, 0),
        'slu+++RL_perturb' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/slu-omp/numeric.cpp', 3427, 6838),
        'lulesh+++fill_sig' : ('', 0, 0),
        'jacobi+++jacobi_step' : ('', 0, 0),
        'background-subtract+++merge' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/background-subtract-omp/main.cpp', 1921, 2632),
        'deredundancy+++kernel_createCutoff' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 7651, 8155),
        'sobol+++sobolGPU_kernel' : ('', 0, 0),
        'gmm+++mstep_covariance2' : ('', 0, 0),
        'sheath+++scatterParticle' : ('', 0, 0),
        'interleave+++add_kernel_non_interleaved' : ('', 0, 0),
        'gd+++L2_norm' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gd-omp/main.cpp', 110, 419),
        'dense-embedding+++dense_esuhm' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/dense-embedding-omp/main.cpp', 784, 1527),
        'gd+++compute' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gd-omp/main.cpp', 423, 1794),
        'rsbench+++lookup' : ('', 0, 0),
        'hexciton+++comm_aosoa_direct' : ('', 0, 0),
        'cross+++cross_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cross-omp/main.cpp', 255, 1209),
        'reaction+++derivative_z2_pbc' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 6052, 7334),
        'cfd+++time_step' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cfd-omp/euler3d.cpp', 13685, 14665),
        'softmax-online+++softmax_forward_online_kernel2' : ('', 0, 0),
        'lid-driven-cavity+++set_horz_pres_BCs' : ('', 0, 0),
        'sobel+++sobel_filter' : ('', 0, 0),
        'crs+++gcrs_m_2_w_5_coding_dotprod' : ('', 0, 0),
        'inversek2j+++invkin_kernel' : ('', 0, 0),
        'deredundancy+++kernel_filter' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 11392, 13227),
        'asmooth+++smoothingFilter' : ('', 0, 0),
        'crs+++gcrs_m_1_w_4_coding_dotprod' : ('', 0, 0),
        'cfd+++initialize_buffer' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cfd-omp/euler3d.cpp', 3983, 21810),
        'lud+++lud_perimeter' : ('', 0, 0),
        'lid-driven-cavity+++sum_pressure' : ('', 0, 0),
        'aligned-types+++testKernel' : ('', 0, 0),
        'tridiagonal+++pcr_branch_free_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/pcr_kernels.cpp', 3122, 5210),
        'tridiagonal+++transpose' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/sweep_kernels.cpp', 7737, 9148),
        'channelSum+++ChannelSumNHWC' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/channelSum-omp/main.cpp', 1017, 1606),
        'hexciton+++comm_manual_aosoa_constants_direct_perm' : ('', 0, 0),
        'deredundancy+++kernel_createIndex6' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 4893, 6272),
        'ddbp+++pad_projections_kernel' : ('', 0, 0),
        'srad+++srad2' : ('', 0, 0),
        'entropy+++entropy' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/entropy-omp/main.cpp', 114, 1185),
        'popcount+++pc6' : ('', 0, 0),
        'babelstream+++nstream_kernel' : ('', 0, 0),
        'ising+++update_lattice' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ising-omp/main.cpp', 1851, 3138),
        'hausdorff+++computeDistance' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hausdorff-omp/main.cpp', 285, 852),
        'fdtd3d+++finite_difference' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/fdtd3d-omp/FDTD3dGPU.cpp', 560, 5013),
        'accuracy+++accuracy_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/accuracy-omp/main.cpp', 143, 953),
        'fpc+++fpc2_kernel' : ('', 0, 0),
        'hexciton+++comm_aosoa_naive_constants_direct' : ('', 0, 0),
        'langford+++dfs_gpu' : ('', 0, 0),
        'reaction+++construct_laplacian' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 8677, 9057),
        'ldpc+++ldpc_cnp_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ldpc-omp/kernel.cpp', 3793, 6876),
        'hogbom+++k_findPeak' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hogbom-omp/kernels.cpp', 643, 1666),
        'ddbp+++img_integration_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 3981, 5811),
        'gd+++update' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gd-omp/main.cpp', 1797, 2208),
        'distort+++barrel_distort' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/distort-omp/distort.cpp', 2252, 2779),
        'gmm+++estep2' : ('', 0, 0),
        'concat+++concat' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/concat-omp/main.cpp', 158, 1003),
        'lsqt+++gpu_apply_hamiltonian' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 4939, 6233),
        'scan2+++prefixSum' : ('', 0, 0),
        'multimaterial+++ccc_loop1_2' : ('', 0, 0),
        'rfs+++sumArrays' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/rfs-omp/main.cpp', 2127, 2640),
        'lanczos+++warp_multiply_kernel' : ('', 0, 0),
        'grep+++parallelMatch' : ('', 0, 0),
        'reverse+++reverse' : ('', 0, 0),
        'hexciton+++comm_manual_aosoa' : ('', 0, 0),
        'bn+++computeKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bn-omp/kernels.cpp', 2053, 4724),
        'hexciton+++comm_aosoa_constants_perm' : ('', 0, 0),
        'kmeans+++find_membership' : ('', 0, 0),
        'lanczos+++dot_product_kernel' : ('', 0, 0),
        'rfs+++sumArray' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/rfs-omp/main.cpp', 1730, 2127),
        'haccmk+++haccmk_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/haccmk-omp/haccmk.cpp', 95, 1607),
        'tridiagonal+++sweep_small_systems_global_vec4_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/sweep_kernels.cpp', 5123, 7328),
        'ddbp+++map_boudaries_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 1917, 2257),
        'nn+++nn' : ('', 0, 0),
        'mrc+++MRCGradient2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mrc-omp/main.cpp', 733, 1288),
        'radixsort+++reorderDataKeysOnlyK' : ('', 0, 0),
        'aobench+++render_kernel' : ('', 0, 0),
        'sad+++get_num_of_occurrences' : ('', 0, 0),
        'babelstream+++mul_kernel' : ('', 0, 0),
        'crs+++gcrs_m_4_w_4_coding_dotprod' : ('', 0, 0),
        'randomAccess+++update' : ('', 0, 0),
        'morphology+++vhgw_horiz' : ('', 0, 0),
        'linearprobing+++k_iterate_hashtable' : ('', 0, 0),
        'ddbp+++differentiation_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ddbp-omp/main.cpp', 8199, 10368),
        'testSNAP+++reset_ulisttot' : ('', 0, 0),
        'atomicPerf+++SingleRangeAtomicOnSharedMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 2733, 3479),
        'chi2+++kernel' : ('', 0, 0),
        'page-rank+++reduce' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/page-rank-omp/main.cpp', 2053, 2730),
        'extend2+++kernel_extend2' : ('', 0, 0),
        'softmax-online+++softmax_forward_baseline_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/softmax-online-omp/main.cpp', 268, 1099),
        'dense-embedding+++dense_esuhm2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/dense-embedding-omp/main.cpp', 1572, 2321),
        'tissue+++tissue' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tissue-omp/main.cpp', 655, 1905),
        'face+++filter_kernel' : ('', 0, 0),
        'atan2+++compute_f' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atan2-omp/main.cpp', 7918, 8466),
        'stddev+++sampleKernel' : ('', 0, 0),
        'extrema+++relextrema_2D' : ('', 0, 0),
        'lulesh+++collect_final_force' : ('', 0, 0),
        'p4+++postprocess' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/p4-omp/main.cpp', 813, 4816),
        'columnarSolver+++decode' : ('', 0, 0),
        'ss+++StringSearchNaive' : ('', 0, 0),
        'michalewicz+++eval' : ('', 0, 0),
        'popcount+++pc4' : ('', 0, 0),
        'eigenvalue+++calNumEigenValueInterval' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/eigenvalue-omp/kernels.cpp', 1922, 2640),
        'stencil3d+++stencil3d' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/stencil3d-omp/main.cpp', 198, 5495),
        'gc+++init' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gc-omp/main.cpp', 2978, 5318),
        'atomicPerf+++WarpRangeAtomicOnSharedMem' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/atomicPerf-omp/main.cpp', 1982, 2710),
        'particles+++bitonicMergeGlobal' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/particles-omp/bitonicSort_kernels.cpp', 6682, 8045),
        'crs+++gcrs_m_2_w_8_coding_dotprod' : ('', 0, 0),
        'cmp+++compute_semblances' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/cmp-omp/main.cpp', 2247, 4289),
        'xlqc+++cuda_mat_J_PI_dp' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/xlqc-omp/cuda_rys_dp.cpp', 76640, 78944),
        'crs+++gcrs_m_1_w_8_coding_dotprod' : ('', 0, 0),
        'rushlarsen+++k_forward_rush_larsen' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/rushlarsen-omp/kernels.cpp', 67, 25770),
        'dxtc2+++compress' : ('', 0, 0),
        'sad+++find_min_in_sad_array' : ('', 0, 0),
        'bwt+++reconstruct_sequence' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/bwt-omp/bwt.cpp', 1263, 1723),
        'stencil1d+++stencil_1d' : ('', 0, 0),
        'dct8x8+++DCT8x8_kernel' : ('', 0, 0),
        'gabor+++gabor' : ('', 0, 0),
        'crs+++gcrs_m_3_w_4_coding_dotprod' : ('', 0, 0),
        'hexciton+++comm_init' : ('', 0, 0),
        'hexciton+++comm_manual_aosoa_constants_direct_prefetch' : ('', 0, 0),
        'srad+++srad' : ('', 0, 0),
        'knn+++cuComputeDistanceGlobal' : ('', 0, 0),
        'lulesh+++calcPositionForNodes' : ('', 0, 0),
        'match+++Match4' : ('', 0, 0),
        'boxfilter+++col_kernel' : ('', 0, 0),
        'swish+++SwishKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/swish-omp/main.cpp', 187, 473),
        'adv+++advCubatureHex3D' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/adv-omp/main.cpp', 533, 6577),
        'sampling+++sampled_rows_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/sampling-omp/main.cpp', 1190, 3438),
        'columnarSolver+++setupKernel' : ('', 0, 0),
        'background-subtract+++updateThreshold' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/background-subtract-omp/main.cpp', 1306, 1841),
        'langevin+++k2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/langevin-omp/main.cpp', 1917, 2460),
        'reaction+++reaction_gray_scott' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/reaction-omp/kernels.cpp', 57, 511),
        'minisweep+++init_faceyz' : ('', 0, 0),
        'hexciton+++comm_refactor_direct_store' : ('', 0, 0),
        'mriQ+++ComputePhiMag_GPU' : ('', 0, 0),
        'lulesh+++accelerationForNode' : ('', 0, 0),
        'all-pairs-distance+++k1' : ('', 0, 0),
        'lid-driven-cavity+++calculate_G' : ('', 0, 0),
        'crs+++gcrs_m_1_w_7_coding_dotprod' : ('', 0, 0),
        'aes+++AESDecrypt' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/aes-omp/kernels.cpp', 4024, 5874),
        'filter+++filter2' : ('', 0, 0),
        'hexciton+++comm_manual_aosoa_constants_perm' : ('', 0, 0),
        'convolutionSeparable+++conv_rows' : ('', 0, 0),
        'gc+++runLarge' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/gc-omp/main.cpp', 5318, 8553),
        'matrix-rotate+++rotate_matrix_parallel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/matrix-rotate-omp/main.cpp', 88, 1243),
        'match+++Match1' : ('', 0, 0),
        'gmm+++seed_clusters_kernel' : ('', 0, 0),
        'entropy+++entropy_opt' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/entropy-omp/main.cpp', 1221, 2644),
        'ising+++init_spins' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ising-omp/main.cpp', 1333, 1799),
        'particles+++bitonicMergeLocal' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/particles-omp/bitonicSort_kernels.cpp', 8152, 10125),
        'gaussian+++fan2' : ('', 0, 0),
        'hexciton+++comm_aosoa_naive_direct' : ('', 0, 0),
        'deredundancy+++kernel_cleanTable' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 9922, 10486),
        'heat+++solve' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/heat-omp/heat.cpp', 2351, 3235),
        'lsqt+++gpu_find_inner_product_2' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/vector.cpp', 8555, 9337),
        'deredundancy+++kernel_createIndex4' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 1985, 3514),
        'hypterm+++hypterm_1' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/hypterm-omp/kernels.cpp', 216, 3450),
        'langevin+++k0' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/langevin-omp/main.cpp', 91, 329),
        'particle-diffusion+++Simulation' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/particle-diffusion-omp/motionsim.cpp', 2405, 4759),
        'fhd+++cmpfhd' : ('', 0, 0),
        'crs+++gcrs_m_3_w_8_coding_dotprod' : ('', 0, 0),
        'minimap2+++device_chain_tiled' : ('', 0, 0),
        'lulesh+++calcStrainRates' : ('', 0, 0),
        'sph+++updatePositions' : ('', 0, 0),
        'testSNAP+++update_ulisttot' : ('', 0, 0),
        'mt+++mt' : ('', 0, 0),
        'mask+++sequenceMaskKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/mask-omp/main.cpp', 250, 1026),
        'resize+++resize_bilinear' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/resize-omp/main.cpp', 2087, 4411),
        'sheath+++pushParticle' : ('', 0, 0),
        'jenkins-hash+++kernel' : ('', 0, 0),
        'aidw+++AIDW_Kernel_Tiled' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/aidw-omp/main.cpp', 3102, 5887),
        'vmc+++initialize' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vmc-omp/vmc.cpp', 3667, 4300),
        'hexciton+++final_gpu_kernel' : ('', 0, 0),
        'ldpc+++ldpc_vnp_kernel_normal' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ldpc-omp/kernel.cpp', 6880, 8496),
        'tridiagonal+++sweep_small_systems_local_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/sweep_kernels.cpp', 634, 2291),
        'lid-driven-cavity+++set_BCs' : ('', 0, 0),
        'softmax-online+++softmax_forward_online_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/softmax-online-omp/main.cpp', 1099, 2579),
        'multimaterial+++ccc_loop3' : ('', 0, 0),
        'lid-driven-cavity+++calculate_u' : ('', 0, 0),
        'bitonic-sort+++bitonic_sort' : ('', 0, 0),
        'channelSum+++ChannelSumNCHW' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/channelSum-omp/main.cpp', 275, 942),
        's8n+++k_cube_select' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/s8n-omp/main.cpp', 134, 1287),
        'match+++Match3' : ('', 0, 0),
        'minisweep+++init_facexz' : ('', 0, 0),
        'vol2col+++vol2col_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/vol2col-omp/main.cpp', 276, 2121),
        'lulesh+++hgc' : ('', 0, 0),
        'radixsort+++radixSortBlocksKeysK' : ('', 0, 0),
        'clenergy+++cenergy' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/clenergy-omp/clenergy.cpp', 748, 3247),
        'amgmk+++relax' : ('', 0, 0),
        'asmooth+++outFilter' : ('', 0, 0),
        'popcount+++pc3' : ('', 0, 0),
        'resize+++resize' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/resize-omp/main.cpp', 185, 2036),
        'deredundancy+++kernel_mergeIndex' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 8155, 8930),
        'deredundancy+++kernel_magic' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 10486, 11388),
        'ace+++swapGrid' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/ace-omp/main.cpp', 8331, 8906),
        'match+++Match9' : ('', 0, 0),
        'hybridsort+++sortElement' : ('', 0, 0),
        'lid-driven-cavity+++calculate_v' : ('', 0, 0),
        'gmm+++mstep_covariance1' : ('', 0, 0),
        'match+++Match7' : ('', 0, 0),
        'pso+++kernelUpdatePBest' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/pso-omp/kernel_gpu.cpp', 1025, 1883),
        'tridiagonal+++cyclic_branch_free_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/tridiagonal-omp/cyclic_kernels.cpp', 3749, 6691),
        'scan+++scan_bcao' : ('', 0, 0),
        'convolution3D+++conv3d_s3' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/convolution3D-omp/main.cpp', 3194, 4609),
        'lsqt+++gpu_apply_commutator' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/lsqt-omp/hamiltonian.cpp', 7810, 8833),
        'eigenvalue+++recalculateEigenIntervals' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/eigenvalue-omp/kernels.cpp', 2640, 4802),
        'deredundancy+++kernel_baseToNumber' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/deredundancy-omp/kernels.cpp', 2, 902),
        'rsc+++RANSAC_kernel_block' : ('', 0, 0),
        'romberg+++romberg' : ('', 0, 0),
        'myocyte+++kernel' : ('', 0, 0),
        'hexciton+++comm_manual_aosoa_constants' : ('', 0, 0),
        'md+++md' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/md-omp/main.cpp', 205, 1482),
        'ans+++phase2_synchronise_blocks' : ('', 0, 0),
        'urng+++noise_uniform' : ('', 0, 0),
        'scel+++SigmoidCrossEntropyWithLogitsKernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/scel-omp/main.cpp', 135, 1066),
        'convolutionSeparable+++conv_cols' : ('', 0, 0),
        'crs+++gcrs_m_1_w_5_coding_dotprod' : ('', 0, 0),
        'diamond+++maskSequences' : ('', 0, 0),
        'crc64+++crc64_kernel' : ('', 0, 0),
        'mdh+++mdh2' : ('', 0, 0),
        'permute+++permute_kernel' : ('/storage/home/hcoda1/7/mdavis438/GANESH-SHARED/HeCBench/src/permute-omp/main.cpp', 586, 1623),
        'knn+++cuParallelSqrt' : ('', 0, 0),
        'crs+++gcrs_m_2_w_7_coding_dotprod' : ('', 0, 0),
        'match+++Match6' : ('', 0, 0),
        'layout+++SoAKernel' : ('', 0, 0),
}

def verify_generation(state, lock, src_code, generation):
    try:
        mapping = cuda_to_openmp_func_mapping[os.path.splitext(os.path.basename(state['src_file']))[0]]
        if mapping == ('', 0, 0):
            return None, 'terminate', 'This function mapping is unimplemented and the translation cannot be verified'
    except:
        return None, 'terminate', 'This function mapping is unimplemented and the translation cannot be verified'

    matches = re.findall(r'```(?:\w+\n)?(.*?)```', generation, re.DOTALL)
    
    if len(matches) < 1:
        return False, 'missing_codeblock', 'Your generation attempt was missing the codeblock surrounded by ```.'

    generation_func = matches[0].strip()
    if '#pragma omp target' not in generation_func:
        return False, 'no_openmp_target_offloading', 'Your generation attempt did not use the Target Offloading capabilities of OpenMP.'
    
    with lock:
        compilation_result = subprocess.run(f"cd {os.path.abspath(os.path.dirname(mapping[0]))} && CC=clang++ make clean", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    
    if not compilation_result.returncode == 0:
        return False, 'terminate', 'This problem is uncompilable using the current syntran script'

    return True, 'success', ''

def verify_syntax(state, lock, src_code, generation):
    mapping = cuda_to_openmp_func_mapping[os.path.splitext(os.path.basename(state['src_file']))[0]]
    matches = re.findall(r'```(?:\w+\n)?(.*?)```', generation, re.DOTALL)
    generation_func = matches[0].strip() if matches else generation
    
    with lock:
        replace_function_index(state['thread_id'], mapping, generation_func)
        compilation_result = subprocess.run(f"cd {os.path.abspath(os.path.dirname(mapping[0]))} && CC=clang++ make clean && CC=clang++ make", shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        undo_function_replacement(state['thread_id'], mapping)

    if not compilation_result.returncode == 0:
        return False, 'compilererror', compilation_result.stderr
    
    return 'success', ''

def verify_semantics(state, lock, src_code, generation):
    mapping = cuda_to_openmp_func_mapping[os.path.splitext(os.path.basename(state['src_file']))[0]]
    matches = re.findall(r'```(?:\w+\n)?(.*?)```', generation, re.DOTALL)
    generation_func = matches[0].strip() if matches else generation

    with lock:
        replace_function_index(state['thread_id'], mapping, generation_func)
        execution_result = subprocess.run(f"cd {os.path.abspath(os.path.dirname(mapping[0]))} && CC=clang++ make run", shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        undo_function_replacement(state['thread_id'], mapping)

    if 'FAIL' in execution_result.stdout:
        return False, 'testerror', execution_result.stdout

    return True, 'success', ''